name: lightelligence-sdk
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nodejs
  - pip
  - pip:
      - -r file:requirements.txt
      - isort == 5.0.4
      - yapf == 0.30.0
      - flake8 == 3.8.3
      - flake8-quotes == 3.2.0
