trigger:
  - master
pr:
  - master

pool: PlatformAgents

jobs:
  - job: "UnitTests"

    steps:
      - bash: |
          ./install_conda_environment.sh update

        displayName: "Update conda env"

      - bash: |
          source ${HOME}/.bashrc lightelligence-sdk
          python -m unittest -v

        displayName: "Run Tests"
